baseURL = "https://kinakomoti-321.github.io/mochimochi3D/"
languageCode = "ja-jp"
title = "MochiMochi3D"
theme = "hugo-blog-jeffprod"
publishDir = "docs"
hasCJKLanguage = true

[taxonomies]
    tag = "tags"
    archive = "archives"

[param]
