baseURL = "http://example.org/"
languageCode = "ja-jp"
title = "3D Memorandom"
theme = "hugo-blog-jeffprod"
publishDir = "docs"

[permalinks]
    post = "/:year/:filename"
[taxonomies]
    tag = "tags"
    archive = "archives"