baseURL = "https://kinakomoti-321.github.io/Memorandom/"
languageCode = "ja-jp"
title = "3D Memorandom"
theme = "hugo-blog-jeffprod"
publishDir = "docs"
hasCJKLanguage = true
[permalinks]
    post = "/:year/:filename"
[taxonomies]
    tag = "tags"
    archive = "archives"